### ISSUE TITLE
Could not find `json`.

### ISSUE THREAD

**Issue by adamviola** [NiklasEi/bevy_common_assets#15]
Just trying to use the `JsonAssetPlugin`:

`use bevy_common_assets::json::JsonAssetPlugin;`

But this won't compile. Here's the error I get:

<img width="828" alt="image" src="https://user-images.githubusercontent.com/43352940/229330407-c6ac93a7-5347-484d-894c-67e3cf2d8b87.png">

Am I doing something wrong? Btw I'm fairly new to Rust.

**Comment by NiklasEi** [comment]
You are likely missing the `json` feature flag. [You need to enable that for the `bevy_common_assets` dependency in your `Cargo.toml` file](https://doc.rust-lang.org/cargo/reference/features.html#dependency-features).

**Comment by adamviola** [comment]
Yep, you're right. Thanks!
