### ISSUE TITLE
Question: correct way to parse several structs from several files?

### ISSUE THREAD

**Issue by CiderSlime** [NiklasEi/bevy_common_assets#20]
I have structs `SpritesData` and `SoundsData`, and I want to parse them from `sprites.data.ron` and `sounds.data.ron` respectively.
A new example would be nice.

**Comment by NiklasEi** [comment]
Since it's different assets, they would get different file endings. E.g.: call the files `name_of_the_sprite.sprite.ron`/`name_of_the_sound.sound.ron` and register the asset loaders with the file names `sprite.ron` and `sound.ron` respectively.

**Comment by NiklasEi** [comment]
Does this answer your question?

**Comment by CiderSlime** [comment]
> Does this answer your question?

Hi! I did it another way. Instead of adding plugin for each .ron format, I used single struct to get it all:
```
struct RonLoadedData {
sprites: Option<SpritesLoadedData>,
sounds: Option<SoundsLoadedData>,
...
```
So I can load different .ron files without requirement to add plugin for each new type.
Maybe it`s a bit unclean, but I like how it works, for now
