### ISSUE TITLE
no `AssetLoader` found for the following extension: yaml

### ISSUE THREAD

**Issue by eatenpancreas** [NiklasEi/bevy_common_assets#23]
`bevy 1.12.1`
Currently figuring out how to use this crate, i added the plugin like so:

```rs
        .add_plugins((
            DefaultPlugins, 
            YamlAssetPlugin::<World>::new(&["world.yml"])
        ))
```

```rs

#[derive(Deserialize, Asset, TypePath, Debug)]
struct World {
    name: String,
    width: u8,
    height: u8,
}


fn load_world(
    server: Res<AssetServer>,
    mut images: ResMut<Assets<Image>>,
    mut worlds: ResMut<Assets<World>>,
    mut commands: Commands
) {
    let handle: Handle<World> = server.load("world.yaml");
    
    if let Some(x) = worlds.get_mut(handle.id()) {
        println!("{:?}", x);
    } else {
        println!("Did not find!")
    }
}



```

This comes up with "did not find!" and the error found in the title: ` ERROR bevy_asset::server: no 'AssetLoader' found for the following extension: yaml` This error also occurs when changing everything to 'yml'.
The yaml file is very simple and as far as i know, this should work?

```yml
name: Cloob
width: 64
height: 32
```

What is going wrong?
Thanks in advance!

Edit: The example contains wrong code, `worlds.get_mut(handle.id())` should be in a `Update` script. It still gives the error regardless.

**Comment by NiklasEi** [comment]
It should work once you rename your file to `xyz.world.yaml`. The plugin configuration defines the file extension `world.yaml`, but if your file is just called `world.yaml`, the extension is only `yaml`.

**Comment by eatenpancreas** [comment]
That worked! Thank you
