### ISSUE TITLE
Support CSV

### ISSUE THREAD

**Issue by eatenpancreas** [NiklasEi/bevy_common_assets#24]
It would be great if there was added support for CSV files, the `csv` crate already has support for serde!

**Comment by NiklasEi** [comment]
I implemented it a bit differently than the other file types since CSV files are tables. The given Asset type is a row, not the whole file (a bit similar to the `LoadedFolder` asset from Bevy).
Is #25 what you were thinking about?

**Comment by eatenpancreas** [comment]
Absolutely! I love it, thank you so much!

I will immediately use it :)
