### ISSUE TITLE
Is there a way to have Handles to other asset types inside the asset?

### ISSUE THREAD

**Issue by Stay1444** [NiklasEi/bevy_common_assets#29]
So I'm trying to replicate something similar to this
```rs
struct Projectile {
    sprite: Handle<Image>
}
```
Where an Asset called Projectile has a reference to another asset inside.

**Comment by NiklasEi** [comment]
At the moment you would do this via the asset path:
```rust
struct Projectile {
    sprite: "sprite.png"
}
```
At some point, Bevy will support stable asset IDs. Then you could do something closer to the example you gave.

**Comment by NiklasEi** [comment]
I will close this for now as there is nothing I can do for this in `bevy_common_assets`.
