### ISSUE TITLE
View the Keep A Changelog spec

### ISSUE THREAD

**Issue by cactusdualcore** [NiklasEi/bevy_common_assets#40]
First and foremost, thanks for having a changelog at all!

I wanted to suggest to look at [Keep A Changelog](https://keepachangelog.com/en/1.1.0/), because I really like that spec for Changelogs and I think it might further improve this projects log. 

If desired, I could try creating the PR for that too :)

**Comment by NiklasEi** [comment]
I personally don't see much value in being stricter in the changelog format for projects as small as this one. Are you missing any specific information in the current informal changelog?

**Comment by cactusdualcore** [comment]
> I personally don't see much value in being stricter in the changelog format for projects as small as this one.

Not to argue with that point, but (as of now) for roughly every 24 downloads of `bevy` on crates.io, there is a download of this crate as well. I think it's safe to say this a pretty important crate in the bevy ecosystem. :P

> Are you missing any specific information in the current informal changelog?

No. I personally just enjoy this kind of standard. If widely adapted, it helps with familiarity and parseability, but there is no need. I simply wanted to suggest it :)
